export const mainnetChains = [
  {
    id: 'ethereum',
    chain_id: 1,
    domain_id: '6648936',
    name: 'Ethereum',
    short_name: 'ETH',
    provider_params: [
      {
        chainId: '0x1',
        chainName: 'Ethereum',
        rpcUrls: ['https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161', 'https://rpc.builder0x69.io'],
        nativeCurrency: {
          name: 'Ethereum',
          symbol: 'ETH',
          decimals: 18,
        },
        blockExplorerUrls: ['https://etherscan.io'],
      },
    ],
    rpc_urls: ['https://eth-mainnet.g.alchemy.com/v2/aWJkilx5wJU1uL2UGOfqQRo4pl_hYyUA'],
    explorer: {
      name: 'Etherscan',
      url: 'https://etherscan.io',
      icon: '/integrations/connext/logos/explorers/etherscan.png',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      contract_0_path: '/address/{address}',
      transaction_path: '/tx/{tx}',
    },
    image: '/integrations/connext/logos/chains/ethereum.png',
    color: '#636890',
    unwrapper_contract: '0x268682b7D9992aE7e2ca4A8bCc9D9655FB06056F',
    group: 'evm',
    no_pool: true,
  },
  {
    id: 'polygon',
    chain_id: 137,
    domain_id: '1886350457',
    name: 'Polygon',
    short_name: 'POLY',
    provider_params: [
      {
        chainId: '0x89',
        chainName: 'Polygon',
        rpcUrls: [
          'https://polygon-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161',
          'https://matic-mainnet.chainstacklabs.com',
          'https://poly-rpc.gateway.pokt.network',
          'https://polygon.blockpi.network/v1/rpc/public',
        ],
        nativeCurrency: {
          name: 'Polygon',
          symbol: 'MATIC',
          decimals: 18,
        },
        blockExplorerUrls: ['https://polygonscan.com'],
      },
    ],
    rpc_urls: ['https://polygon-mainnet.g.alchemy.com/v2/aA2cuymyI9ip0I1spb1nURVWdfOC5aVM'],
    explorer: {
      name: 'Polygonscan',
      url: 'https://polygonscan.com',
      icon: '/integrations/connext/logos/explorers/polygonscan.png',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      contract_0_path: '/address/{address}',
      transaction_path: '/tx/{tx}',
    },
    image: '/integrations/connext/logos/chains/polygon.png',
    color: '#8247e5',
    unwrapper_contract: '0x7E8F8B2dA3dc5Ad9c9Dfd1A832331A039d4f3f74',
    group: 'evm',
  },
  {
    id: 'optimism',
    chain_id: 10,
    domain_id: '1869640809',
    name: 'Optimism',
    short_name: 'OPT',
    provider_params: [
      {
        chainId: '0xa',
        chainName: 'Optimism',
        rpcUrls: ['https://optimism-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161', 'https://optimism.blockpi.network/v1/rpc/public'],
        nativeCurrency: {
          name: 'Ethereum',
          symbol: 'oETH',
          decimals: 18,
        },
        blockExplorerUrls: ['https://optimistic.etherscan.io'],
      },
    ],
    rpc_urls: ['https://opt-mainnet.g.alchemy.com/v2/0oboZqHgeVJlfqVEl6-CoZUpESdns_4W'],
    explorer: {
      name: 'Etherscan',
      url: 'https://optimistic.etherscan.io',
      icon: '/integrations/connext/logos/explorers/optimism.png',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      contract_0_path: '/address/{address}',
      transaction_path: '/tx/{tx}',
    },
    image: '/integrations/connext/logos/chains/optimism.png',
    color: '#dc2626',
    unwrapper_contract: '0x7Fe09d217d646a6213e51b237670Bc326188cB93',
    group: 'optimistic_rollups',
  },
  {
    id: 'arbitrum',
    chain_id: 42161,
    domain_id: '1634886255',
    name: 'Arbitrum',
    short_name: 'ARB',
    provider_params: [
      {
        chainId: '0xa4b1',
        chainName: 'Arbitrum One',
        rpcUrls: [
          'https://arbitrum-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161',
          'https://arbitrum.blockpi.network/v1/rpc/public',
          'https://arb1.arbitrum.io/rpc',
        ],
        nativeCurrency: {
          name: 'Ethereum',
          symbol: 'aETH',
          decimals: 18,
        },
        blockExplorerUrls: ['https://arbiscan.io'],
      },
    ],
    rpc_urls: ['https://arb-mainnet.g.alchemy.com/v2/TdexEsMvH_cEqRkAHKzDT6ssagS1_mc_'],
    explorer: {
      name: 'Arbiscan',
      url: 'https://arbiscan.io',
      icon: '/integrations/connext/logos/explorers/arbiscan.png',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      contract_0_path: '/address/{address}',
      transaction_path: '/tx/{tx}',
    },
    image: '/integrations/connext/logos/chains/arbitrum.png',
    color: '#28a0f0',
    unwrapper_contract: '0x429b9eb01362b2799131EfCC44319689b662999D',
    group: 'optimistic_rollups',
  },
  {
    id: 'gnosis',
    chain_id: 100,
    domain_id: '6778479',
    name: 'Gnosis',
    short_name: 'GNO',
    provider_params: [
      {
        chainId: '0x64',
        chainName: 'Gnosis',
        rpcUrls: [
          'https://gnosis.blockpi.network/v1/rpc/public',
          'https://rpc.gnosis.gateway.fm',
          'https://rpc.gnosischain.com',
          'https://rpc.ankr.com/gnosis',
          'https://xdai-rpc.gateway.pokt.network',
          'https://gnosischain-rpc.gateway.pokt.network',
        ],
        nativeCurrency: {
          name: 'xDAI',
          symbol: 'xDAI',
          decimals: 18,
        },
        blockExplorerUrls: ['https://gnosisscan.io'],
      },
    ],
    rpc_urls: ['https://gnosis.blockpi.network/v1/rpc/public'],
    explorer: {
      name: 'Gnosisscan',
      url: 'https://gnosisscan.io',
      icon: '/integrations/connext/logos/explorers/gnosisscan.png',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      contract_0_path: '/address/{address}',
      transaction_path: '/tx/{tx}',
    },
    image: '/integrations/connext/logos/chains/gnosis.png',
    color: '#48a9a6',
    unwrapper_contract: '0x642c27a96dFFB6f21443A89b789a3194Ff8399fa',
    group: 'evm',
  },
]
