export const arweaveAccountFormControls = [
  {
    formfieldName: 'handleName',
    component: 'input',
    label: 'Handle Name',
    placeholder: 'Insert your @ here',
  },
  {
    formfieldName: 'name',
    component: 'input',
    label: 'Name',
    placeholder: 'Insert your name here',
  },
  {
    formfieldName: 'bio',
    component: 'textArea',
    label: 'Bio',
    placeholder: 'Insert your bio here',
  },
  {
    formfieldName: 'email',
    component: 'input',
    label: 'Email Address',
    placeholder: 'Insert your Email here',
  },
  {
    formfieldName: 'wallets.eth',
    component: 'input',
    label: 'Etheruem address',
    placeholder: 'Insert your Etheruem address here',
  },
  {
    formfieldName: 'links.twitter',
    component: 'input',
    label: 'Twitter link',
    placeholder: 'Insert your Twitter link here',
  },
  {
    formfieldName: 'links.github',
    component: 'input',
    label: 'Github link',
    placeholder: 'Insert your Github link here',
  },
  {
    formfieldName: 'links.instagram',
    component: 'input',
    label: 'Instagram link',
    placeholder: 'Insert your Instagram link here',
  },
  {
    formfieldName: 'links.discord',
    component: 'input',
    label: 'Discord link',
    placeholder: 'Insert your Discord link here',
  },
  {
    formfieldName: 'links.facebook',
    component: 'input',
    label: 'Facebook link',
    placeholder: 'Insert your Facebook link here',
  },
  {
    formfieldName: 'links.linkedin',
    component: 'input',
    label: 'LinkedIn link',
    placeholder: 'Insert your LinkedIn link here',
  },
  {
    formfieldName: 'links.youtube',
    component: 'input',
    label: 'Youtube link',
    placeholder: 'Insert your Youtube link here',
  },
  {
    formfieldName: 'links.twitch',
    component: 'input',
    label: 'Twitch link',
    placeholder: 'Insert your Twitch link here',
  },
]
