// Generated by @wagmi/cli@1.1.0 on 6/8/2023 at 8:47:42 AM
import {
  UseContractEventConfig,
  UseContractReadConfig,
  UseContractWriteConfig,
  UsePrepareContractWriteConfig,
  useContractEvent,
  useContractRead,
  useContractWrite,
  usePrepareContractWrite,
} from 'wagmi'
import { PrepareWriteContractResult, ReadContractResult, WriteContractMode } from 'wagmi/actions'

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// poolTogetherPrizePool
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const poolTogetherPrizePoolABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      { name: '_owner', internalType: 'address', type: 'address' },
      { name: '_yieldSource', internalType: 'contract IYieldSource', type: 'address' },
    ],
  },
  { type: 'event', anonymous: false, inputs: [{ name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false }], name: 'AwardCaptured' },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'winner', internalType: 'address', type: 'address', indexed: true },
      { name: 'token', internalType: 'contract ITicket', type: 'address', indexed: true },
      { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'Awarded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'winner', internalType: 'address', type: 'address', indexed: true },
      { name: 'token', internalType: 'address', type: 'address', indexed: true },
      { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'AwardedExternalERC20',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'winner', internalType: 'address', type: 'address', indexed: true },
      { name: 'token', internalType: 'address', type: 'address', indexed: true },
      { name: 'tokenIds', internalType: 'uint256[]', type: 'uint256[]', indexed: false },
    ],
    name: 'AwardedExternalERC721',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'balanceCap', internalType: 'uint256', type: 'uint256', indexed: false }],
    name: 'BalanceCapSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'token', internalType: 'contract ITicket', type: 'address', indexed: true }],
    name: 'ControlledTokenAdded',
  },
  { type: 'event', anonymous: false, inputs: [{ name: 'yieldSource', internalType: 'address', type: 'address', indexed: true }], name: 'Deployed' },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'operator', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'token', internalType: 'contract ITicket', type: 'address', indexed: true },
      { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'Deposited',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'error', internalType: 'bytes', type: 'bytes', indexed: false }],
    name: 'ErrorAwardingExternalERC721',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'liquidityCap', internalType: 'uint256', type: 'uint256', indexed: false }],
    name: 'LiquidityCapSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'pendingOwner', internalType: 'address', type: 'address', indexed: true }],
    name: 'OwnershipOffered',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'previousOwner', internalType: 'address', type: 'address', indexed: true },
      { name: 'newOwner', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'prizeStrategy', internalType: 'address', type: 'address', indexed: true }],
    name: 'PrizeStrategySet',
  },
  { type: 'event', anonymous: false, inputs: [{ name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false }], name: 'Swept' },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'ticket', internalType: 'contract ITicket', type: 'address', indexed: true }],
    name: 'TicketSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'token', internalType: 'address', type: 'address', indexed: true },
      { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'TransferredExternalERC20',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'operator', internalType: 'address', type: 'address', indexed: true },
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'token', internalType: 'contract ITicket', type: 'address', indexed: true },
      { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'redeemed', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'Withdrawal',
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'VERSION', outputs: [{ name: '', internalType: 'string', type: 'string' }] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_to', internalType: 'address', type: 'address' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'award',
    outputs: [],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'awardBalance', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_to', internalType: 'address', type: 'address' },
      { name: '_externalToken', internalType: 'address', type: 'address' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'awardExternalERC20',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_to', internalType: 'address', type: 'address' },
      { name: '_externalToken', internalType: 'address', type: 'address' },
      { name: '_tokenIds', internalType: 'uint256[]', type: 'uint256[]' },
    ],
    name: 'awardExternalERC721',
    outputs: [],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'balance', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_externalToken', internalType: 'address', type: 'address' }],
    name: 'canAwardExternal',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'captureAwardBalance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'claimOwnership', outputs: [] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_compLike', internalType: 'contract ICompLike', type: 'address' },
      { name: '_to', internalType: 'address', type: 'address' },
    ],
    name: 'compLikeDelegate',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_to', internalType: 'address', type: 'address' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'depositTo',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_to', internalType: 'address', type: 'address' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
      { name: '_delegate', internalType: 'address', type: 'address' },
    ],
    name: 'depositToAndDelegate',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'getAccountedBalance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'getBalanceCap', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'getLiquidityCap',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'getPrizeStrategy',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'getTicket',
    outputs: [{ name: '', internalType: 'contract ITicket', type: 'address' }],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'getToken', outputs: [{ name: '', internalType: 'address', type: 'address' }] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_controlledToken', internalType: 'contract ITicket', type: 'address' }],
    name: 'isControlled',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'pure',
    type: 'function',
    inputs: [
      { name: '', internalType: 'address', type: 'address' },
      { name: '', internalType: 'address', type: 'address' },
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'onERC721Received',
    outputs: [{ name: '', internalType: 'bytes4', type: 'bytes4' }],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'owner', outputs: [{ name: '', internalType: 'address', type: 'address' }] },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'pendingOwner', outputs: [{ name: '', internalType: 'address', type: 'address' }] },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'renounceOwnership', outputs: [] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_balanceCap', internalType: 'uint256', type: 'uint256' }],
    name: 'setBalanceCap',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_liquidityCap', internalType: 'uint256', type: 'uint256' }],
    name: 'setLiquidityCap',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_prizeStrategy', internalType: 'address', type: 'address' }],
    name: 'setPrizeStrategy',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_ticket', internalType: 'contract ITicket', type: 'address' }],
    name: 'setTicket',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'sweep', outputs: [] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_to', internalType: 'address', type: 'address' },
      { name: '_externalToken', internalType: 'address', type: 'address' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferExternalERC20',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_from', internalType: 'address', type: 'address' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'withdrawFrom',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'yieldSource',
    outputs: [{ name: '', internalType: 'contract IYieldSource', type: 'address' }],
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// React
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__.
 */
export function usePoolTogetherPrizePoolRead<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"VERSION"`.
 */
export function usePoolTogetherPrizePoolVersion<
  TFunctionName extends 'VERSION',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'VERSION', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"awardBalance"`.
 */
export function usePoolTogetherPrizePoolAwardBalance<
  TFunctionName extends 'awardBalance',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'awardBalance', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"canAwardExternal"`.
 */
export function usePoolTogetherPrizePoolCanAwardExternal<
  TFunctionName extends 'canAwardExternal',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'canAwardExternal', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"getAccountedBalance"`.
 */
export function usePoolTogetherPrizePoolGetAccountedBalance<
  TFunctionName extends 'getAccountedBalance',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'getAccountedBalance', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"getBalanceCap"`.
 */
export function usePoolTogetherPrizePoolGetBalanceCap<
  TFunctionName extends 'getBalanceCap',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'getBalanceCap', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"getLiquidityCap"`.
 */
export function usePoolTogetherPrizePoolGetLiquidityCap<
  TFunctionName extends 'getLiquidityCap',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'getLiquidityCap', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"getPrizeStrategy"`.
 */
export function usePoolTogetherPrizePoolGetPrizeStrategy<
  TFunctionName extends 'getPrizeStrategy',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'getPrizeStrategy', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"getTicket"`.
 */
export function usePoolTogetherPrizePoolGetTicket<
  TFunctionName extends 'getTicket',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'getTicket', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"getToken"`.
 */
export function usePoolTogetherPrizePoolGetToken<
  TFunctionName extends 'getToken',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'getToken', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"isControlled"`.
 */
export function usePoolTogetherPrizePoolIsControlled<
  TFunctionName extends 'isControlled',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'isControlled', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"onERC721Received"`.
 */
export function usePoolTogetherPrizePoolOnErc721Received<
  TFunctionName extends 'onERC721Received',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'onERC721Received', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"owner"`.
 */
export function usePoolTogetherPrizePoolOwner<
  TFunctionName extends 'owner',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'owner', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"pendingOwner"`.
 */
export function usePoolTogetherPrizePoolPendingOwner<
  TFunctionName extends 'pendingOwner',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'pendingOwner', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"yieldSource"`.
 */
export function usePoolTogetherPrizePoolYieldSource<
  TFunctionName extends 'yieldSource',
  TSelectData = ReadContractResult<typeof poolTogetherPrizePoolABI, TFunctionName>
>(config: Omit<UseContractReadConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TSelectData>, 'abi' | 'functionName'> = {} as any) {
  return useContractRead({ abi: poolTogetherPrizePoolABI, functionName: 'yieldSource', ...config } as UseContractReadConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__.
 */
export function usePoolTogetherPrizePoolWrite<TFunctionName extends string, TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, string>['request']['abi'], TFunctionName, TMode>
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, TFunctionName, TMode> & {
        abi?: never
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, TFunctionName, TMode>({ abi: poolTogetherPrizePoolABI, ...config } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"award"`.
 */
export function usePoolTogetherPrizePoolAward<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'award'>['request']['abi'], 'award', TMode> & {
        functionName?: 'award'
      }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'award', TMode> & {
        abi?: never
        functionName?: 'award'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'award', TMode>({ abi: poolTogetherPrizePoolABI, functionName: 'award', ...config } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"awardExternalERC20"`.
 */
export function usePoolTogetherPrizePoolAwardExternalErc20<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'awardExternalERC20'>['request']['abi'],
        'awardExternalERC20',
        TMode
      > & { functionName?: 'awardExternalERC20' }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'awardExternalERC20', TMode> & {
        abi?: never
        functionName?: 'awardExternalERC20'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'awardExternalERC20', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'awardExternalERC20',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"awardExternalERC721"`.
 */
export function usePoolTogetherPrizePoolAwardExternalErc721<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'awardExternalERC721'>['request']['abi'],
        'awardExternalERC721',
        TMode
      > & { functionName?: 'awardExternalERC721' }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'awardExternalERC721', TMode> & {
        abi?: never
        functionName?: 'awardExternalERC721'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'awardExternalERC721', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'awardExternalERC721',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"balance"`.
 */
export function usePoolTogetherPrizePoolBalance<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'balance'>['request']['abi'], 'balance', TMode> & {
        functionName?: 'balance'
      }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'balance', TMode> & {
        abi?: never
        functionName?: 'balance'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'balance', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'balance',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"captureAwardBalance"`.
 */
export function usePoolTogetherPrizePoolCaptureAwardBalance<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'captureAwardBalance'>['request']['abi'],
        'captureAwardBalance',
        TMode
      > & { functionName?: 'captureAwardBalance' }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'captureAwardBalance', TMode> & {
        abi?: never
        functionName?: 'captureAwardBalance'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'captureAwardBalance', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'captureAwardBalance',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"claimOwnership"`.
 */
export function usePoolTogetherPrizePoolClaimOwnership<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'claimOwnership'>['request']['abi'],
        'claimOwnership',
        TMode
      > & { functionName?: 'claimOwnership' }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'claimOwnership', TMode> & {
        abi?: never
        functionName?: 'claimOwnership'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'claimOwnership', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'claimOwnership',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"compLikeDelegate"`.
 */
export function usePoolTogetherPrizePoolCompLikeDelegate<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'compLikeDelegate'>['request']['abi'],
        'compLikeDelegate',
        TMode
      > & { functionName?: 'compLikeDelegate' }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'compLikeDelegate', TMode> & {
        abi?: never
        functionName?: 'compLikeDelegate'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'compLikeDelegate', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'compLikeDelegate',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"depositTo"`.
 */
export function usePoolTogetherPrizePoolDepositTo<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'depositTo'>['request']['abi'], 'depositTo', TMode> & {
        functionName?: 'depositTo'
      }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'depositTo', TMode> & {
        abi?: never
        functionName?: 'depositTo'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'depositTo', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'depositTo',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"depositToAndDelegate"`.
 */
export function usePoolTogetherPrizePoolDepositToAndDelegate<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'depositToAndDelegate'>['request']['abi'],
        'depositToAndDelegate',
        TMode
      > & { functionName?: 'depositToAndDelegate' }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'depositToAndDelegate', TMode> & {
        abi?: never
        functionName?: 'depositToAndDelegate'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'depositToAndDelegate', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'depositToAndDelegate',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"renounceOwnership"`.
 */
export function usePoolTogetherPrizePoolRenounceOwnership<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'renounceOwnership'>['request']['abi'],
        'renounceOwnership',
        TMode
      > & { functionName?: 'renounceOwnership' }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'renounceOwnership', TMode> & {
        abi?: never
        functionName?: 'renounceOwnership'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'renounceOwnership', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'renounceOwnership',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"setBalanceCap"`.
 */
export function usePoolTogetherPrizePoolSetBalanceCap<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'setBalanceCap'>['request']['abi'],
        'setBalanceCap',
        TMode
      > & { functionName?: 'setBalanceCap' }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'setBalanceCap', TMode> & {
        abi?: never
        functionName?: 'setBalanceCap'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'setBalanceCap', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'setBalanceCap',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"setLiquidityCap"`.
 */
export function usePoolTogetherPrizePoolSetLiquidityCap<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'setLiquidityCap'>['request']['abi'],
        'setLiquidityCap',
        TMode
      > & { functionName?: 'setLiquidityCap' }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'setLiquidityCap', TMode> & {
        abi?: never
        functionName?: 'setLiquidityCap'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'setLiquidityCap', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'setLiquidityCap',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"setPrizeStrategy"`.
 */
export function usePoolTogetherPrizePoolSetPrizeStrategy<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'setPrizeStrategy'>['request']['abi'],
        'setPrizeStrategy',
        TMode
      > & { functionName?: 'setPrizeStrategy' }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'setPrizeStrategy', TMode> & {
        abi?: never
        functionName?: 'setPrizeStrategy'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'setPrizeStrategy', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'setPrizeStrategy',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"setTicket"`.
 */
export function usePoolTogetherPrizePoolSetTicket<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'setTicket'>['request']['abi'], 'setTicket', TMode> & {
        functionName?: 'setTicket'
      }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'setTicket', TMode> & {
        abi?: never
        functionName?: 'setTicket'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'setTicket', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'setTicket',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"sweep"`.
 */
export function usePoolTogetherPrizePoolSweep<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'sweep'>['request']['abi'], 'sweep', TMode> & {
        functionName?: 'sweep'
      }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'sweep', TMode> & {
        abi?: never
        functionName?: 'sweep'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'sweep', TMode>({ abi: poolTogetherPrizePoolABI, functionName: 'sweep', ...config } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"transferExternalERC20"`.
 */
export function usePoolTogetherPrizePoolTransferExternalErc20<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'transferExternalERC20'>['request']['abi'],
        'transferExternalERC20',
        TMode
      > & { functionName?: 'transferExternalERC20' }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'transferExternalERC20', TMode> & {
        abi?: never
        functionName?: 'transferExternalERC20'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'transferExternalERC20', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'transferExternalERC20',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"transferOwnership"`.
 */
export function usePoolTogetherPrizePoolTransferOwnership<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'transferOwnership'>['request']['abi'],
        'transferOwnership',
        TMode
      > & { functionName?: 'transferOwnership' }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'transferOwnership', TMode> & {
        abi?: never
        functionName?: 'transferOwnership'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'transferOwnership', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'transferOwnership',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"withdrawFrom"`.
 */
export function usePoolTogetherPrizePoolWithdrawFrom<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<PrepareWriteContractResult<typeof poolTogetherPrizePoolABI, 'withdrawFrom'>['request']['abi'], 'withdrawFrom', TMode> & {
        functionName?: 'withdrawFrom'
      }
    : UseContractWriteConfig<typeof poolTogetherPrizePoolABI, 'withdrawFrom', TMode> & {
        abi?: never
        functionName?: 'withdrawFrom'
      } = {} as any
) {
  return useContractWrite<typeof poolTogetherPrizePoolABI, 'withdrawFrom', TMode>({
    abi: poolTogetherPrizePoolABI,
    functionName: 'withdrawFrom',
    ...config,
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__.
 */
export function usePreparePoolTogetherPrizePoolWrite<TFunctionName extends string>(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, TFunctionName>, 'abi'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    TFunctionName
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"award"`.
 */
export function usePreparePoolTogetherPrizePoolAward(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'award'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'award', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'award'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"awardExternalERC20"`.
 */
export function usePreparePoolTogetherPrizePoolAwardExternalErc20(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'awardExternalERC20'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'awardExternalERC20', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'awardExternalERC20'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"awardExternalERC721"`.
 */
export function usePreparePoolTogetherPrizePoolAwardExternalErc721(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'awardExternalERC721'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'awardExternalERC721', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'awardExternalERC721'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"balance"`.
 */
export function usePreparePoolTogetherPrizePoolBalance(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'balance'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'balance', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'balance'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"captureAwardBalance"`.
 */
export function usePreparePoolTogetherPrizePoolCaptureAwardBalance(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'captureAwardBalance'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'captureAwardBalance', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'captureAwardBalance'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"claimOwnership"`.
 */
export function usePreparePoolTogetherPrizePoolClaimOwnership(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'claimOwnership'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'claimOwnership', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'claimOwnership'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"compLikeDelegate"`.
 */
export function usePreparePoolTogetherPrizePoolCompLikeDelegate(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'compLikeDelegate'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'compLikeDelegate', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'compLikeDelegate'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"depositTo"`.
 */
export function usePreparePoolTogetherPrizePoolDepositTo(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'depositTo'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'depositTo', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'depositTo'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"depositToAndDelegate"`.
 */
export function usePreparePoolTogetherPrizePoolDepositToAndDelegate(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'depositToAndDelegate'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'depositToAndDelegate', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'depositToAndDelegate'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"renounceOwnership"`.
 */
export function usePreparePoolTogetherPrizePoolRenounceOwnership(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'renounceOwnership'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'renounceOwnership', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'renounceOwnership'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"setBalanceCap"`.
 */
export function usePreparePoolTogetherPrizePoolSetBalanceCap(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'setBalanceCap'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'setBalanceCap', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'setBalanceCap'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"setLiquidityCap"`.
 */
export function usePreparePoolTogetherPrizePoolSetLiquidityCap(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'setLiquidityCap'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'setLiquidityCap', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'setLiquidityCap'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"setPrizeStrategy"`.
 */
export function usePreparePoolTogetherPrizePoolSetPrizeStrategy(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'setPrizeStrategy'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'setPrizeStrategy', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'setPrizeStrategy'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"setTicket"`.
 */
export function usePreparePoolTogetherPrizePoolSetTicket(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'setTicket'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'setTicket', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'setTicket'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"sweep"`.
 */
export function usePreparePoolTogetherPrizePoolSweep(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'sweep'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'sweep', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'sweep'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"transferExternalERC20"`.
 */
export function usePreparePoolTogetherPrizePoolTransferExternalErc20(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'transferExternalERC20'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'transferExternalERC20', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'transferExternalERC20'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"transferOwnership"`.
 */
export function usePreparePoolTogetherPrizePoolTransferOwnership(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'transferOwnership'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'transferOwnership', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'transferOwnership'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `functionName` set to `"withdrawFrom"`.
 */
export function usePreparePoolTogetherPrizePoolWithdrawFrom(
  config: Omit<UsePrepareContractWriteConfig<typeof poolTogetherPrizePoolABI, 'withdrawFrom'>, 'abi' | 'functionName'> = {} as any
) {
  return usePrepareContractWrite({ abi: poolTogetherPrizePoolABI, functionName: 'withdrawFrom', ...config } as UsePrepareContractWriteConfig<
    typeof poolTogetherPrizePoolABI,
    'withdrawFrom'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__.
 */
export function usePoolTogetherPrizePoolEvent<TEventName extends string>(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, TEventName>, 'abi'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, ...config } as UseContractEventConfig<typeof poolTogetherPrizePoolABI, TEventName>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"AwardCaptured"`.
 */
export function usePoolTogetherPrizePoolAwardCapturedEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'AwardCaptured'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'AwardCaptured', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'AwardCaptured'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"Awarded"`.
 */
export function usePoolTogetherPrizePoolAwardedEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'Awarded'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'Awarded', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'Awarded'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"AwardedExternalERC20"`.
 */
export function usePoolTogetherPrizePoolAwardedExternalErc20Event(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'AwardedExternalERC20'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'AwardedExternalERC20', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'AwardedExternalERC20'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"AwardedExternalERC721"`.
 */
export function usePoolTogetherPrizePoolAwardedExternalErc721Event(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'AwardedExternalERC721'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'AwardedExternalERC721', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'AwardedExternalERC721'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"BalanceCapSet"`.
 */
export function usePoolTogetherPrizePoolBalanceCapSetEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'BalanceCapSet'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'BalanceCapSet', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'BalanceCapSet'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"ControlledTokenAdded"`.
 */
export function usePoolTogetherPrizePoolControlledTokenAddedEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'ControlledTokenAdded'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'ControlledTokenAdded', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'ControlledTokenAdded'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"Deployed"`.
 */
export function usePoolTogetherPrizePoolDeployedEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'Deployed'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'Deployed', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'Deployed'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"Deposited"`.
 */
export function usePoolTogetherPrizePoolDepositedEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'Deposited'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'Deposited', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'Deposited'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"ErrorAwardingExternalERC721"`.
 */
export function usePoolTogetherPrizePoolErrorAwardingExternalErc721Event(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'ErrorAwardingExternalERC721'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'ErrorAwardingExternalERC721', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'ErrorAwardingExternalERC721'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"LiquidityCapSet"`.
 */
export function usePoolTogetherPrizePoolLiquidityCapSetEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'LiquidityCapSet'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'LiquidityCapSet', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'LiquidityCapSet'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"OwnershipOffered"`.
 */
export function usePoolTogetherPrizePoolOwnershipOfferedEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'OwnershipOffered'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'OwnershipOffered', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'OwnershipOffered'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"OwnershipTransferred"`.
 */
export function usePoolTogetherPrizePoolOwnershipTransferredEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'OwnershipTransferred'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'OwnershipTransferred', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'OwnershipTransferred'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"PrizeStrategySet"`.
 */
export function usePoolTogetherPrizePoolPrizeStrategySetEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'PrizeStrategySet'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'PrizeStrategySet', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'PrizeStrategySet'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"Swept"`.
 */
export function usePoolTogetherPrizePoolSweptEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'Swept'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'Swept', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'Swept'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"TicketSet"`.
 */
export function usePoolTogetherPrizePoolTicketSetEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'TicketSet'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'TicketSet', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'TicketSet'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"TransferredExternalERC20"`.
 */
export function usePoolTogetherPrizePoolTransferredExternalErc20Event(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'TransferredExternalERC20'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'TransferredExternalERC20', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'TransferredExternalERC20'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link poolTogetherPrizePoolABI}__ and `eventName` set to `"Withdrawal"`.
 */
export function usePoolTogetherPrizePoolWithdrawalEvent(
  config: Omit<UseContractEventConfig<typeof poolTogetherPrizePoolABI, 'Withdrawal'>, 'abi' | 'eventName'> = {} as any
) {
  return useContractEvent({ abi: poolTogetherPrizePoolABI, eventName: 'Withdrawal', ...config } as UseContractEventConfig<
    typeof poolTogetherPrizePoolABI,
    'Withdrawal'
  >)
}
