export const publicLockV13Abi = [
  { type: 'error', inputs: [], name: 'CANNOT_APPROVE_SELF' },
  { type: 'error', inputs: [], name: 'CANT_BE_SMALLER_THAN_SUPPLY' },
  { type: 'error', inputs: [], name: 'CANT_EXTEND_NON_EXPIRING_KEY' },
  { type: 'error', inputs: [], name: 'GAS_REFUND_FAILED' },
  { type: 'error', inputs: [], name: 'INSUFFICIENT_ERC20_VALUE' },
  { type: 'error', inputs: [], name: 'INSUFFICIENT_VALUE' },
  { type: 'error', inputs: [], name: 'INVALID_ADDRESS' },
  { type: 'error', inputs: [{ name: 'hookIndex', internalType: 'uint8', type: 'uint8' }], name: 'INVALID_HOOK' },
  { type: 'error', inputs: [], name: 'INVALID_LENGTH' },
  { type: 'error', inputs: [], name: 'INVALID_TOKEN' },
  { type: 'error', inputs: [], name: 'KEY_NOT_VALID' },
  { type: 'error', inputs: [], name: 'KEY_TRANSFERS_DISABLED' },
  { type: 'error', inputs: [], name: 'LOCK_HAS_CHANGED' },
  { type: 'error', inputs: [], name: 'LOCK_SOLD_OUT' },
  { type: 'error', inputs: [], name: 'MAX_KEYS_REACHED' },
  { type: 'error', inputs: [], name: 'MIGRATION_REQUIRED' },
  { type: 'error', inputs: [], name: 'NON_COMPLIANT_ERC721_RECEIVER' },
  { type: 'error', inputs: [], name: 'NON_RENEWABLE_LOCK' },
  { type: 'error', inputs: [], name: 'NOT_ENOUGH_FUNDS' },
  { type: 'error', inputs: [], name: 'NOT_ENOUGH_TIME' },
  { type: 'error', inputs: [], name: 'NOT_READY_FOR_RENEWAL' },
  { type: 'error', inputs: [], name: 'NO_SUCH_KEY' },
  { type: 'error', inputs: [], name: 'NULL_VALUE' },
  { type: 'error', inputs: [], name: 'ONLY_KEY_MANAGER_OR_APPROVED' },
  { type: 'error', inputs: [], name: 'ONLY_LOCK_MANAGER' },
  { type: 'error', inputs: [], name: 'ONLY_LOCK_MANAGER_OR_KEY_GRANTER' },
  { type: 'error', inputs: [], name: 'OUT_OF_RANGE' },
  { type: 'error', inputs: [], name: 'OWNER_CANT_BE_ADDRESS_ZERO' },
  { type: 'error', inputs: [], name: 'SCHEMA_VERSION_NOT_CORRECT' },
  { type: 'error', inputs: [], name: 'TRANSFER_TO_SELF' },
  { type: 'error', inputs: [], name: 'TransferFailed' },
  { type: 'error', inputs: [], name: 'UNAUTHORIZED' },
  { type: 'error', inputs: [], name: 'UNAUTHORIZED_KEY_MANAGER_UPDATE' },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address', indexed: true },
      { name: 'approved', internalType: 'address', type: 'address', indexed: true },
      { name: 'tokenId', internalType: 'uint256', type: 'uint256', indexed: true },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address', indexed: true },
      { name: 'operator', internalType: 'address', type: 'address', indexed: true },
      { name: 'approved', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'ApprovalForAll',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'tokenId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'owner', internalType: 'address', type: 'address', indexed: true },
      { name: 'sendTo', internalType: 'address', type: 'address', indexed: true },
      { name: 'refund', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'CancelKey',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'onKeyPurchaseHook', internalType: 'address', type: 'address', indexed: false },
      { name: 'onKeyCancelHook', internalType: 'address', type: 'address', indexed: false },
      { name: 'onValidKeyHook', internalType: 'address', type: 'address', indexed: false },
      { name: 'onTokenURIHook', internalType: 'address', type: 'address', indexed: false },
      { name: 'onKeyTransferHook', internalType: 'address', type: 'address', indexed: false },
      { name: 'onKeyExtendHook', internalType: 'address', type: 'address', indexed: false },
      { name: 'onKeyGrantHook', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'EventHooksUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'tokenId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'newExpiration', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'timeAdded', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'ExpirationChanged',
  },
  { type: 'event', anonymous: false, inputs: [{ name: 'tokenId', internalType: 'uint256', type: 'uint256', indexed: true }], name: 'ExpireKey' },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'refundValue', internalType: 'uint256', type: 'uint256', indexed: false }],
    name: 'GasRefundValueChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'receiver', internalType: 'address', type: 'address', indexed: true },
      { name: 'refundedAmount', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'tokenAddress', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'GasRefunded',
  },
  { type: 'event', anonymous: false, inputs: [{ name: 'version', internalType: 'uint8', type: 'uint8', indexed: false }], name: 'Initialized' },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'tokenId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'newTimestamp', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'KeyExtended',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'account', internalType: 'address', type: 'address', indexed: true }],
    name: 'KeyGranterAdded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'account', internalType: 'address', type: 'address', indexed: true }],
    name: 'KeyGranterRemoved',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: '_tokenId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: '_newManager', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'KeyManagerChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'updatedRecordsCount', internalType: 'uint256', type: 'uint256', indexed: false }],
    name: 'KeysMigrated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'expirationDuration', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'maxNumberOfKeys', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'maxKeysPerAcccount', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'LockConfig',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'account', internalType: 'address', type: 'address', indexed: true }],
    name: 'LockManagerAdded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'account', internalType: 'address', type: 'address', indexed: true }],
    name: 'LockManagerRemoved',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'name', internalType: 'string', type: 'string', indexed: false },
      { name: 'symbol', internalType: 'string', type: 'string', indexed: false },
      { name: 'baseTokenURI', internalType: 'string', type: 'string', indexed: false },
    ],
    name: 'LockMetadata',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'previousOwner', internalType: 'address', type: 'address', indexed: false },
      { name: 'newOwner', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'oldKeyPrice', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'keyPrice', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'oldTokenAddress', internalType: 'address', type: 'address', indexed: false },
      { name: 'tokenAddress', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'PricingChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'referrer', internalType: 'address', type: 'address', indexed: true },
      { name: 'fee', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'ReferrerFee',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'freeTrialLength', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'refundPenaltyBasisPoints', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'RefundPenaltyChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'previousAdminRole', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'newAdminRole', internalType: 'bytes32', type: 'bytes32', indexed: true },
    ],
    name: 'RoleAdminChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'account', internalType: 'address', type: 'address', indexed: true },
      { name: 'sender', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'RoleGranted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'account', internalType: 'address', type: 'address', indexed: true },
      { name: 'sender', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'RoleRevoked',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'tokenId', internalType: 'uint256', type: 'uint256', indexed: true },
    ],
    name: 'Transfer',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'transferFeeBasisPoints', internalType: 'uint256', type: 'uint256', indexed: false }],
    name: 'TransferFeeChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'lockAddress', internalType: 'address', type: 'address', indexed: true },
      { name: 'unlockAddress', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'UnlockCallFailed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'sender', internalType: 'address', type: 'address', indexed: true },
      { name: 'tokenAddress', internalType: 'address', type: 'address', indexed: true },
      { name: 'recipient', internalType: 'address', type: 'address', indexed: true },
      { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'Withdrawal',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'DEFAULT_ADMIN_ROLE',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'addLockManager',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_approved', internalType: 'address', type: 'address' },
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_keyOwner', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: 'balance', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'burn',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'cancelAndRefund',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'expirationDuration',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'expireAndRefundFor',
    outputs: [],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: '_value', internalType: 'uint256', type: 'uint256' },
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
      { name: '_referrer', internalType: 'address', type: 'address' },
      { name: '_data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'extend',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'freeTrialLength',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'gasRefundValue',
    outputs: [{ name: '_refundValue', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'getApproved',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'getCancelAndRefundValue',
    outputs: [{ name: 'refund', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_keyOwner', internalType: 'address', type: 'address' }],
    name: 'getHasValidKey',
    outputs: [{ name: 'isValid', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'role', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getRoleAdmin',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
      { name: '_time', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getTransferFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
      { name: '_duration', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'grantKeyExtension',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_recipients', internalType: 'address[]', type: 'address[]' },
      { name: '_expirationTimestamps', internalType: 'uint256[]', type: 'uint256[]' },
      { name: '_keyManagers', internalType: 'address[]', type: 'address[]' },
    ],
    name: 'grantKeys',
    outputs: [{ name: '', internalType: 'uint256[]', type: 'uint256[]' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32' },
      { name: 'account', internalType: 'address', type: 'address' },
    ],
    name: 'grantRole',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32' },
      { name: 'account', internalType: 'address', type: 'address' },
    ],
    name: 'hasRole',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_lockCreator', internalType: 'address payable', type: 'address' },
      { name: '_expirationDuration', internalType: 'uint256', type: 'uint256' },
      { name: '_tokenAddress', internalType: 'address', type: 'address' },
      { name: '_keyPrice', internalType: 'uint256', type: 'uint256' },
      { name: '_maxNumberOfKeys', internalType: 'uint256', type: 'uint256' },
      { name: '_lockName', internalType: 'string', type: 'string' },
    ],
    name: 'initialize',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '_owner', internalType: 'address', type: 'address' },
      { name: '_operator', internalType: 'address', type: 'address' },
    ],
    name: 'isApprovedForAll',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'isLockManager',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'isOwner',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
      { name: '_referrer', internalType: 'address', type: 'address' },
    ],
    name: 'isRenewable',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'isValidKey',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'keyExpirationTimestampFor',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'keyManagerOf',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'keyPrice', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_from', internalType: 'address', type: 'address' },
      { name: '_recipient', internalType: 'address', type: 'address' },
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'lendKey',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'maxKeysPerAddress',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'maxNumberOfKeys',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_tokenIdFrom', internalType: 'uint256', type: 'uint256' },
      { name: '_tokenIdTo', internalType: 'uint256', type: 'uint256' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'mergeKeys',
    outputs: [],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [{ name: '', internalType: 'bytes', type: 'bytes' }], name: 'migrate', outputs: [] },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'name', outputs: [{ name: '', internalType: 'string', type: 'string' }] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'numberOfOwners',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'onKeyCancelHook',
    outputs: [{ name: '', internalType: 'contract ILockKeyCancelHook', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'onKeyExtendHook',
    outputs: [{ name: '', internalType: 'contract ILockKeyExtendHook', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'onKeyGrantHook',
    outputs: [{ name: '', internalType: 'contract ILockKeyGrantHook', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'onKeyPurchaseHook',
    outputs: [{ name: '', internalType: 'contract ILockKeyPurchaseHook', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'onKeyTransferHook',
    outputs: [{ name: '', internalType: 'contract ILockKeyTransferHook', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'onTokenURIHook',
    outputs: [{ name: '', internalType: 'contract ILockTokenURIHook', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'onValidKeyHook',
    outputs: [{ name: '', internalType: 'contract ILockValidKeyHook', type: 'address' }],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'owner', outputs: [{ name: '', internalType: 'address', type: 'address' }] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'pure',
    type: 'function',
    inputs: [],
    name: 'publicLockVersion',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: '_values', internalType: 'uint256[]', type: 'uint256[]' },
      { name: '_recipients', internalType: 'address[]', type: 'address[]' },
      { name: '_referrers', internalType: 'address[]', type: 'address[]' },
      { name: '_keyManagers', internalType: 'address[]', type: 'address[]' },
      { name: '_data', internalType: 'bytes[]', type: 'bytes[]' },
    ],
    name: 'purchase',
    outputs: [{ name: '', internalType: 'uint256[]', type: 'uint256[]' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '_recipient', internalType: 'address', type: 'address' },
      { name: '_referrer', internalType: 'address', type: 'address' },
      { name: '_data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'purchasePriceFor',
    outputs: [{ name: 'minKeyPrice', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'referrerFees',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'refundPenaltyBasisPoints',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
      { name: '_referrer', internalType: 'address', type: 'address' },
    ],
    name: 'renewMembershipFor',
    outputs: [],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'renounceLockManager', outputs: [] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32' },
      { name: 'account', internalType: 'address', type: 'address' },
    ],
    name: 'renounceRole',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32' },
      { name: 'account', internalType: 'address', type: 'address' },
    ],
    name: 'revokeRole',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_from', internalType: 'address', type: 'address' },
      { name: '_to', internalType: 'address', type: 'address' },
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_from', internalType: 'address', type: 'address' },
      { name: '_to', internalType: 'address', type: 'address' },
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
      { name: '_data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'schemaVersion', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_to', internalType: 'address', type: 'address' },
      { name: '_approved', internalType: 'bool', type: 'bool' },
    ],
    name: 'setApprovalForAll',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_onKeyPurchaseHook', internalType: 'address', type: 'address' },
      { name: '_onKeyCancelHook', internalType: 'address', type: 'address' },
      { name: '_onValidKeyHook', internalType: 'address', type: 'address' },
      { name: '_onTokenURIHook', internalType: 'address', type: 'address' },
      { name: '_onKeyTransferHook', internalType: 'address', type: 'address' },
      { name: '_onKeyExtendHook', internalType: 'address', type: 'address' },
      { name: '_onKeyGrantHook', internalType: 'address', type: 'address' },
    ],
    name: 'setEventHooks',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_refundValue', internalType: 'uint256', type: 'uint256' }],
    name: 'setGasRefundValue',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
      { name: '_keyManager', internalType: 'address', type: 'address' },
    ],
    name: 'setKeyManagerOf',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_lockName', internalType: 'string', type: 'string' },
      { name: '_lockSymbol', internalType: 'string', type: 'string' },
      { name: '_baseTokenURI', internalType: 'string', type: 'string' },
    ],
    name: 'setLockMetadata',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'setOwner',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_referrer', internalType: 'address', type: 'address' },
      { name: '_feeBasisPoint', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'setReferrerFee',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_to', internalType: 'address', type: 'address' },
      { name: '_tokenIdFrom', internalType: 'uint256', type: 'uint256' },
      { name: '_timeShared', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'shareKey',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'interfaceId', internalType: 'bytes4', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'symbol', outputs: [{ name: '', internalType: 'string', type: 'string' }] },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'tokenAddress', outputs: [{ name: '', internalType: 'address', type: 'address' }] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_index', internalType: 'uint256', type: 'uint256' }],
    name: 'tokenByIndex',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '_keyOwner', internalType: 'address', type: 'address' },
      { name: '_index', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'tokenOfOwnerByIndex',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_keyOwner', internalType: 'address', type: 'address' }],
    name: 'totalKeys',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '_totalKeysCreated', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'transferFeeBasisPoints',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_from', internalType: 'address', type: 'address' },
      { name: '_recipient', internalType: 'address', type: 'address' },
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_recipient', internalType: 'address', type: 'address' },
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'unlendKey',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'unlockProtocol',
    outputs: [{ name: '', internalType: 'contract IUnlock', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_keyPrice', internalType: 'uint256', type: 'uint256' },
      { name: '_tokenAddress', internalType: 'address', type: 'address' },
    ],
    name: 'updateKeyPricing',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_newExpirationDuration', internalType: 'uint256', type: 'uint256' },
      { name: '_maxNumberOfKeys', internalType: 'uint256', type: 'uint256' },
      { name: '_maxKeysPerAcccount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'updateLockConfig',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_freeTrialLength', internalType: 'uint256', type: 'uint256' },
      { name: '_refundPenaltyBasisPoints', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'updateRefundPenalty',
    outputs: [],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'updateSchemaVersion', outputs: [] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_transferFeeBasisPoints', internalType: 'uint256', type: 'uint256' }],
    name: 'updateTransferFee',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_tokenAddress', internalType: 'address', type: 'address' },
      { name: '_recipient', internalType: 'address payable', type: 'address' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'withdraw',
    outputs: [],
  },
  { stateMutability: 'payable', type: 'receive' },
] as const
