export const unlockV12Abi = [
  { type: 'error', inputs: [], name: 'Unlock__ALREADY_DEPLOYED' },
  { type: 'error', inputs: [], name: 'Unlock__INVALID_AMOUNT' },
  { type: 'error', inputs: [], name: 'Unlock__MANAGER_ONLY' },
  { type: 'error', inputs: [{ name: 'lockAddress', internalType: 'address', type: 'address' }], name: 'Unlock__MISSING_LOCK' },
  { type: 'error', inputs: [], name: 'Unlock__MISSING_LOCK_TEMPLATE' },
  { type: 'error', inputs: [], name: 'Unlock__MISSING_PROXY_ADMIN' },
  { type: 'error', inputs: [], name: 'Unlock__MISSING_TEMPLATE' },
  { type: 'error', inputs: [], name: 'Unlock__VERSION_TOO_HIGH' },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'udt', internalType: 'address', type: 'address', indexed: false },
      { name: 'weth', internalType: 'address', type: 'address', indexed: false },
      { name: 'estimatedGasForPurchase', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'globalTokenSymbol', internalType: 'string', type: 'string', indexed: false },
      { name: 'globalTokenURI', internalType: 'string', type: 'string', indexed: false },
      { name: 'chainId', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'ConfigUnlock',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'grossNetworkProduct', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: '_valueInETH', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'tokenAddress', internalType: 'address', type: 'address', indexed: false },
      { name: 'value', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'lockAddress', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'GNPChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'lockAddress', internalType: 'address', type: 'address', indexed: false },
      { name: 'version', internalType: 'uint16', type: 'uint16', indexed: false },
    ],
    name: 'LockUpgraded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'lockOwner', internalType: 'address', type: 'address', indexed: true },
      { name: 'newLockAddress', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'NewLock',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'previousOwner', internalType: 'address', type: 'address', indexed: true },
      { name: 'newOwner', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'grossNetworkProduct', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'totalDiscountGranted', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'ResetTrackedValue',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'publicLockAddress', internalType: 'address', type: 'address', indexed: false }],
    name: 'SetLockTemplate',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'impl', internalType: 'address', type: 'address', indexed: true },
      { name: 'version', internalType: 'uint16', type: 'uint16', indexed: true },
    ],
    name: 'UnlockTemplateAdded',
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'sender', internalType: 'address', type: 'address' }],
    name: '__initializeOwnable',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'impl', internalType: 'address', type: 'address' },
      { name: 'version', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'addLockTemplate',
    outputs: [],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'chainId', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }] },
  {
    stateMutability: 'pure',
    type: 'function',
    inputs: [
      { name: '', internalType: 'address', type: 'address' },
      { name: '', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'computeAvailableDiscountFor',
    outputs: [
      { name: 'discount', internalType: 'uint256', type: 'uint256' },
      { name: 'tokens', internalType: 'uint256', type: 'uint256' },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_udt', internalType: 'address', type: 'address' },
      { name: '_weth', internalType: 'address', type: 'address' },
      { name: '_estimatedGasForPurchase', internalType: 'uint256', type: 'uint256' },
      { name: '_symbol', internalType: 'string', type: 'string' },
      { name: '_URI', internalType: 'string', type: 'string' },
      { name: '_chainId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'configUnlock',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_expirationDuration', internalType: 'uint256', type: 'uint256' },
      { name: '_tokenAddress', internalType: 'address', type: 'address' },
      { name: '_keyPrice', internalType: 'uint256', type: 'uint256' },
      { name: '_maxNumberOfKeys', internalType: 'uint256', type: 'uint256' },
      { name: '_lockName', internalType: 'string', type: 'string' },
      { name: '', internalType: 'bytes12', type: 'bytes12' },
    ],
    name: 'createLock',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'data', internalType: 'bytes', type: 'bytes' }],
    name: 'createUpgradeableLock',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'data', internalType: 'bytes', type: 'bytes' },
      { name: '_lockVersion', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'createUpgradeableLockAtVersion',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'estimatedGasForPurchase',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'getAdmin', outputs: [{ name: '', internalType: 'address', type: 'address' }] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'getGlobalBaseTokenURI',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'getGlobalTokenSymbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'globalBaseTokenURI',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'globalTokenSymbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'grossNetworkProduct',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_unlockOwner', internalType: 'address', type: 'address' }],
    name: 'initialize',
    outputs: [],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'initializeProxyAdmin', outputs: [] },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'isOwner', outputs: [{ name: '', internalType: 'bool', type: 'bool' }] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'locks',
    outputs: [
      { name: 'deployed', internalType: 'bool', type: 'bool' },
      { name: 'totalSales', internalType: 'uint256', type: 'uint256' },
      { name: 'yieldedDiscountTokens', internalType: 'uint256', type: 'uint256' },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'networkBaseFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'owner', outputs: [{ name: '', internalType: 'address', type: 'address' }] },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'postLockUpgrade', outputs: [] },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'protocolFee', outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'proxyAdminAddress',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'publicLockAddress',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_version', internalType: 'uint16', type: 'uint16' }],
    name: 'publicLockImpls',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'publicLockLatestVersion',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_impl', internalType: 'address', type: 'address' }],
    name: 'publicLockVersions',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'recordConsumedDiscount',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_value', internalType: 'uint256', type: 'uint256' },
      { name: '_referrer', internalType: 'address', type: 'address' },
    ],
    name: 'recordKeyPurchase',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'lock', internalType: 'address', type: 'address' }],
    name: 'removeLock',
    outputs: [],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'renounceOwnership', outputs: [] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_grossNetworkProduct', internalType: 'uint256', type: 'uint256' },
      { name: '_totalDiscountGranted', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'resetTrackedValue',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_publicLockAddress', internalType: 'address', type: 'address' }],
    name: 'setLockTemplate',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_tokenAddress', internalType: 'address', type: 'address' },
      { name: '_oracleAddress', internalType: 'address', type: 'address' },
    ],
    name: 'setOracle',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_protocolFee', internalType: 'uint256', type: 'uint256' }],
    name: 'setProtocolFee',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalDiscountGranted',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferTokens',
    outputs: [],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'udt', outputs: [{ name: '', internalType: 'address', type: 'address' }] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'uniswapOracles',
    outputs: [{ name: '', internalType: 'contract IUniswapOracleV3', type: 'address' }],
  },
  { stateMutability: 'pure', type: 'function', inputs: [], name: 'unlockVersion', outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'lockAddress', internalType: 'address payable', type: 'address' },
      { name: 'version', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'upgradeLock',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  { stateMutability: 'view', type: 'function', inputs: [], name: 'weth', outputs: [{ name: '', internalType: 'address', type: 'address' }] },
  { stateMutability: 'payable', type: 'receive' },
] as const
